### ISSUE TITLE
Clock Display Options disable new quest notifications

### ISSUE THREAD

**Issue by KariArisu** [Enerrex/ItsStardewTime#1]
A quest progress pop-up was added in the 1.6 update, but using any of the options under "Clock Display" completely removes this functionality.

Picture of the pop-up:
![image](https://github.com/Enerrex/ItsStardewTime/assets/3825742/5398439d-e83b-49a0-8580-b09b6752d4b8)

Disabling all of the clock display options brings it back. Figured this out after a lot of troubleshooting -- removing mods until I figured out which mod caused it and then diagnosing the mod options.

Posting this on github and nexusmods for visibility, not sure if this is something you can fix.

**Comment by Enerrex** [comment]
Hmm that explains that. I saw the quest progress pop-up when playing unmodded with friends but noticed it was gone in singleplayer. Not sure what is causing that, but the original mod does do some patching on the UI especially that display area. The new quest progress dialog may be part of this.

I will try to look into it sometime but can't promise much. Would be happy to review any changes if someone pushes any.

**Comment by Enerrex** [comment]
I think I found the why to this problem. It's pretty nasty, it looks like the "DayTimeMoneyBox" which handles the clock among other things, also helps render the quest pop-up, has its functionality patched by this mod. The mod patched the original render code to just include the updated time options, by straight up copying the method to handle all of its logic with the needed bits sprinkled in. So I'd need to essentially re-do that process with the newer DayTimeMoneyBox render logic. I'll see what that would entail effort wise this weekend most likely.

**Comment by KariArisu** [comment]
Oof that sounds rough. Hopefully you can figure it out, it's completely beyond me at least. If not oh well, it's a minor annoyance.
